#!/usr/bin/env python3
"""PRISM-UI bundler: src/*.luau -> dist/PRISM.luau (single executor-ready file).

Rewrites intra-library require("Name") calls to a tiny embedded module loader
and concatenates the modules in dependency order. Verifies that no bare
require() calls survive and that every module returned a table.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
DIST = ROOT / "dist"

# Dependency order: every module only requires modules listed before it.
ORDER = [
    "Color",
    "Signal",
    "Theme",
    "Util",
    "Schema",
    "Store",
    "Widgets",
    "ColorPicker",
    "Panel",
    "Window",
    "Init",
]

REQUIRE_RE = re.compile(r'require\("(?:\./)?([A-Za-z0-9_]+)"\)')


def load_module(name: str) -> str:
    path = SRC / f"{name}.luau"
    if not path.exists():
        sys.exit(f"bundle: missing {path}")
    text = path.read_text(encoding="utf-8")

    def swap(m: re.Match) -> str:
        dep = m.group(1)
        if dep not in ORDER:
            sys.exit(f"bundle: {name} requires unknown module '{dep}'")
        if ORDER.index(dep) >= ORDER.index(name):
            sys.exit(f"bundle: {name} requires '{dep}' which comes later (cycle/order)")
        return f'__PRISM_REQUIRE("{dep}")'

    text = REQUIRE_RE.sub(swap, text)
    # Drop the per-file typecheck pragma (the bundle carries one at the top).
    lines = [ln for ln in text.splitlines(keepends=False) if ln.strip() != "--!strict"]
    return "\n".join(lines).strip() + "\n"


def main() -> None:
    parts = []
    for name in ORDER:
        body = load_module(name)
        parts.append(f'__PRISM_MODULES["{name}"] = (function()\n{body}end)()\n')

    bundle = []
    bundle.append("--!strict")
    bundle.append("-- " + "=" * 74)
    bundle.append("--  PRISM-UI v1.0.0 · single-file build (generated by tools/bundle.py)")
    bundle.append("--  Usage: local PRISM = loadstring(readfile(\"PRISM.luau\"))()")
    bundle.append("--         local app = PRISM.new({ profile = \"Legit\" })")
    bundle.append("-- " + "=" * 74)
    bundle.append("")
    bundle.append("local __PRISM_MODULES = {}")
    bundle.append("local function __PRISM_REQUIRE(name: string): any")
    bundle.append('    local m = __PRISM_MODULES[name]')
    bundle.append('    assert(m ~= nil, "PRISM: module \'" .. name .. "\' not loaded")')
    bundle.append("    return m")
    bundle.append("end")
    bundle.append("")
    bundle.extend(p.strip("\n") for p in parts)
    bundle.append("")
    bundle.append('return __PRISM_MODULES["Init"]')
    bundle.append("")
    out = "\n".join(bundle)

    # Safety: no bare require() may survive (would fail in executors).
    leftovers = [ln for ln in out.splitlines() if 'require("' in ln and "__PRISM_REQUIRE" not in ln]
    if leftovers:
        sys.exit(f"bundle: {len(leftovers)} bare require() calls survived:\n" + "\n".join(leftovers[:5]))

    DIST.mkdir(exist_ok=True)
    target = DIST / "PRISM.luau"
    target.write_text(out, encoding="utf-8")
    print(f"bundle: wrote {target} ({len(out)} bytes, {out.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
